;; -*- mode: emacs-lisp -*-

(source melpa)

(depends-on "cmake-mode")
(depends-on "company")
(depends-on "company-c-headers")
(depends-on "expand-region")
(depends-on "ede-compdb")
(depends-on "find-file-in-project")
(depends-on "flycheck")
(depends-on "goto-last-change")
(depends-on "htmlize")
(depends-on "ibuffer-vc")
(depends-on "iedit")
(depends-on "magit")
(depends-on "markdown-mode")
(depends-on "session")
(depends-on "smartparens")
(depends-on "ssh-config-mode")
(depends-on "yasnippet")
(depends-on "projectile")
(depends-on "google-c-style")

(source org)

;(depends-on "org")
; Use this instead (see https://github.com/cask/cask/issues/119)
(depends-on "org-plus-contrib")
