;; -*- mode: emacs-lisp -*-

(source melpa)

(depends-on "cmake-mode")
(depends-on "company")
(depends-on "expand-region")
(depends-on "find-file-in-project")
(depends-on "flymake")
(depends-on "flymake-cursor")
(depends-on "goto-last-change")
(depends-on "iedit")
(depends-on "magit")
(depends-on "markdown-mode")
(depends-on "session")
(depends-on "smartparens")
(depends-on "ssh-config-mode")

(source org)

;(depends-on "org")
; Use this instead (see https://github.com/cask/cask/issues/119)
(depends-on "org-plus-contrib")
